const {remote}=require('webdriverio'); const {spawn,execFileSync}=require('child_process'); const fs=require('fs'); const path=require('path'); const http=require('http');
const APP=path.join(process.env.LOCALAPPDATA,'LedgerLens','ledgerlens.exe'), DRIVER=path.join(process.env.USERPROFILE,'.cargo','bin','tauri-driver.exe'), DL=path.join(process.env.USERPROFILE,'Downloads');
const NOTE='=SUM(A1:A2) +123 -123 @test <review> & synthetic note'; const results=[]; const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const rec=(n,p,d='')=>{results.push({name:n,pass:p,detail:d});console.log(`[${p?'PASS':'FAIL'}] ${n} — ${d}`)};
function kill(){try{execFileSync('powershell.exe',['-NoProfile','-Command','Get-Process ledgerlens,ledgerlens-backend,tauri-driver,msedgedriver -ErrorAction SilentlyContinue|Stop-Process -Force'],{stdio:'ignore'})}catch{}}
function count(){try{return Number(execFileSync('powershell.exe',['-NoProfile','-Command','@(Get-Process ledgerlens,ledgerlens-backend,tauri-driver,msedgedriver -ErrorAction SilentlyContinue).Count'],{encoding:'utf8'}).trim()||0)}catch{return 0}}
function ping(){return new Promise(r=>{let q=http.get('http://127.0.0.1:8001/api/firm',x=>{let b='';x.on('data',c=>b+=c);x.on('end',()=>r(x.statusCode===200))});q.on('error',()=>r(false));q.setTimeout(2000,()=>{q.destroy();r(false)})})}
async function wait(){for(let i=0;i<60;i++){if(await ping())return true;await sleep(1000)}return false}
async function session(){let d=spawn(DRIVER,['--port','4444'],{stdio:'ignore'});await sleep(1500);let b=await remote({hostname:'127.0.0.1',port:4444,path:'/',capabilities:{'tauri:options':{application:APP}}});await wait();return{b,d}}
async function click(b,id){let e=await b.$(`[data-testid="${id}"]`);await e.waitForDisplayed({timeout:30000});await e.click();return e}
async function act(b,cat,id,label,note=false){await click(b,`exception-category-${cat}`);let c=await b.$('[data-testid="exception-card-item"]');await c.waitForDisplayed({timeout:15000});await c.click();await click(b,id);await b.waitUntil(async()=>await c.getText().then(t=>t.includes(label)),{timeout:15000});if(note){let f=await b.$('[data-testid="finding-note-input"]');await f.setValue(NOTE);await click(b,'save-note-button');await sleep(800)}return c.getText()}
async function main(){kill();await sleep(1000);let b,d;try{({b,d}=await session());let cont=await b.$('button*=Continue to App');if(await cont.isExisting())await cont.click();await click(b,'nav-clients');let reviews=await b.$$('button*=Review');let enabled=null;for(const x of reviews){if(await x.isEnabled()){enabled=x;break}}if(!enabled)throw Error('No completed scan available in UI');await enabled.click();let cards=await b.$$('[data-testid="exception-card-item"]');rec('Open Review Center through UI',cards.length>=4,`${cards.length} cards`);
rec('Click Keep', (await act(b,'exact_duplicate','mark-keep-button','Keep')).includes('Keep'));rec('Click Keep Both',(await act(b,'unreadable','mark-keep-both-button','Keep Both')).includes('Keep Both'));rec('Click Ignore',(await act(b,'possible_duplicate','mark-ignore-button','Ignore')).includes('Ignore'));rec('Click Review Later and Save Note',(await act(b,'wrong_period','mark-review-later-button','Review Later',true)).includes('Review Later'));
await click(b,'nav-reports');await click(b,'nav-review_center');for(const [cat,label] of [['exact_duplicate','Keep'],['unreadable','Keep Both'],['possible_duplicate','Ignore'],['wrong_period','Review Later']]){await click(b,`exception-category-${cat}`);let c=await b.$('[data-testid="exception-card-item"]');await c.waitForDisplayed({timeout:15000});rec(`${label} visible after UI reload`,(await c.getText()).includes(label));if(cat==='wrong_period'){await c.click();rec('Note visible after UI reload',(await b.$('[data-testid="finding-note-input"]').getValue())===NOTE)}}
await click(b,'review-export-button');for(const [fmt,id,ext] of [['CSV','export-csv-button','.csv'],['XLSX','export-xlsx-button','.xlsx'],['PDF','export-pdf-button','.pdf']]){let before=new Set(fs.readdirSync(DL));await click(b,id);let found=null;for(let i=0;i<40;i++){await sleep(500);found=fs.readdirSync(DL).find(n=>!before.has(n)&&n.toLowerCase().endsWith(ext));if(found)break}rec(`Click ${fmt} export`,!!found,found||'no downloaded file')}
await b.deleteSession();b=null;if(d)d.kill();d=null;await sleep(3000);rec('No orphan processes after WebDriver close',count()===0,`${count()} processes`);
let s=spawn(APP,[],{detached:true,stdio:'ignore'});s.unref();rec('Normal relaunch backend reconnects',await wait());kill();await sleep(2000);rec('No orphan processes after forced full close',count()===0,`${count()} processes`);
}catch(e){rec('Continuation failure',false,e.stack||e.message)}finally{if(b)try{await b.deleteSession()}catch{};if(d)try{d.kill()}catch{};kill()}fs.writeFileSync('final_ui_review_results.json',JSON.stringify(results,null,2));let p=results.filter(x=>x.pass).length;console.log(`FINAL ${p}/${results.length}`);process.exit(p===results.length?0:1)}main();