const { remote } = require('webdriverio');
const { spawn, execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const http = require('http');

const APP = path.join(process.env.LOCALAPPDATA, 'LedgerLens', 'ledgerlens.exe');
const DRIVER = path.join(process.env.USERPROFILE, '.cargo', 'bin', 'tauri-driver.exe');
const DOWNLOADS = path.join(process.env.USERPROFILE, 'Downloads');
const SOURCE = 'C:\\Users\\acer\\Desktop\\data\\synthetic-finance-data-main\\1\\synthetic-finance-data-main\\output';
const CLIENT = 'Upload_Security_Test';
const NOTE = 'Final independent UI verification < > & =SUM(A1:A2) @test';
const results = [];
const sleep = ms => new Promise(r => setTimeout(r, ms));
function rec(name, pass, detail='', method='REAL INSTALLED UI'){ results.push({name,pass,detail,method}); console.log(`[${pass?'PASS':'FAIL'}] ${name} — ${detail}`); }
function kill(){ try{execFileSync('powershell.exe',['-NoProfile','-Command','Get-Process ledgerlens,ledgerlens-backend,tauri-driver,msedgedriver -ErrorAction SilentlyContinue | Stop-Process -Force'],{stdio:'ignore'});}catch{} }
function pcount(){ try{return Number(execFileSync('powershell.exe',['-NoProfile','-Command','@(Get-Process ledgerlens,ledgerlens-backend,tauri-driver,msedgedriver -ErrorAction SilentlyContinue).Count'],{encoding:'utf8'}).trim()||0)}catch{return 0} }
function get(route, timeout=5000){return new Promise(r=>{let q=http.get('http://127.0.0.1:8001'+route,x=>{let b='';x.on('data',c=>b+=c);x.on('end',()=>{try{r({status:x.statusCode,data:JSON.parse(b)})}catch{r({status:x.statusCode,raw:b})}})});q.on('error',()=>r(null));q.setTimeout(timeout,()=>{q.destroy();r(null)})})}
async function waitBackend(seconds=60){for(let i=0;i<seconds;i++){let x=await get('/api/firm',2000);if(x?.status===200)return true;await sleep(1000)}return false}
async function session(){let d=spawn(DRIVER,['--port','4444'],{stdio:'ignore'});await sleep(1500);let b=await remote({hostname:'127.0.0.1',port:4444,path:'/',capabilities:{'tauri:options':{application:APP}}});let up=await waitBackend();return{b,d,up}}
async function click(b,id){let e=await b.$(`[data-testid="${id}"]`);await e.waitForDisplayed({timeout:30000});await e.click();return e}
async function enterApp(b){let c=await b.$('button*=Continue to App');if(await c.isExisting())await c.click()}
async function openClientReview(b,name){await click(b,'nav-clients');let card=await b.$(`//*[contains(@data-testid,'client-card-') and contains(.,"${name}")]`);await card.waitForDisplayed({timeout:30000});let r=await card.$('button*=Review');await r.click();await b.$('[data-testid="findings-list"]').waitForDisplayed({timeout:30000});return card}
async function categoryCards(b,cat){await click(b,`exception-category-${cat}`);await sleep(300);return await b.$$('[data-testid="exception-card-item"]')}
async function setDecision(b,cat,index,button,label,note=false){let cards=await categoryCards(b,cat);if(cards.length<=index)throw Error(`not enough ${cat} cards`);let c=cards[index];await c.click();await click(b,button);await b.waitUntil(async()=>await c.getText().then(t=>t.includes(label)),{timeout:15000});if(note){let f=await b.$('[data-testid="finding-note-input"]');await f.setValue(NOTE);await click(b,'save-note-button');await sleep(700)}return await c.getText()}
async function exportSet(b,tag){await click(b,'review-export-button');let files=[];for(const [fmt,id,ext] of [['CSV','export-csv-button','.csv'],['XLSX','export-xlsx-button','.xlsx'],['PDF','export-pdf-button','.pdf']]){let expected=path.join(DOWNLOADS,`review_report_${CLIENT}.${ext.slice(1)}`);if(fs.existsSync(expected))fs.renameSync(expected,path.join(__dirname,`prior_${Date.now()}_${path.basename(expected)}`));await click(b,id);for(let i=0;i<30&&!fs.existsSync(expected);i++)await sleep(500);let ok=fs.existsSync(expected)&&fs.statSync(expected).size>0;rec(`${tag} ${fmt} export`,ok,ok?`${expected} ${fs.statSync(expected).size} bytes`:'missing');if(ok)files.push(expected)}return files}
async function deleteChecks(b){await click(b,'nav-clients');await click(b,'add-client-button');let n=`Delete_UI_QA_${Date.now()}`;await b.$('[data-testid="client-name-input"]').then(x=>x.setValue(n));await click(b,'client-create-submit');await sleep(800);let card=await b.$(`//*[contains(@data-testid,'client-card-') and contains(.,"${n}")]`);await card.waitForDisplayed({timeout:15000});let id=(await card.getAttribute('data-testid')).replace('client-card-','');
await click(b,`delete-client-${id}`);await click(b,'delete-step1-cancel');rec('Delete step 1 Cancel preserves client',await card.isExisting(),n);
await click(b,`delete-client-${id}`);await click(b,'delete-step1-continue');await click(b,'delete-step2-keep');rec('Delete step 2 Keep It preserves client',await card.isExisting(),n);
await click(b,`delete-client-${id}`);await click(b,'delete-step1-continue');await click(b,'delete-step2-confirm');await b.waitUntil(async()=>!(await card.isExisting()),{timeout:15000});rec('Delete Permanently removes LedgerLens record',!(await card.isExisting()),n);
}
(async()=>{kill();await sleep(1000);let b,d;try{({b,d,up}=await session());rec('Installed app launches', (await b.getTitle()).includes('LedgerLens'), await b.getTitle());rec('Bundled backend starts',up,'127.0.0.1:8001','API/BACKEND');let sys=await get('/api/system-check',120000);rec('SQLite health',sys?.data?.checks?.find(x=>x.id==='sqlite')?.status==='PASS','system-check','API/BACKEND');rec('Local-only health',sys?.data?.checks?.find(x=>x.id==='offline')?.status==='PASS','system-check','API/BACKEND');await enterApp(b);let privacy=await b.$('[data-testid="privacy-status-badge"]');rec('Local-only badge visible',(await privacy.getText()).includes('Local'),await privacy.getText());await openClientReview(b,CLIENT);let cards=await b.$$('[data-testid="exception-card-item"]');rec('32-file scan findings appear',cards.length===25,`${cards.length} findings`);
rec('Keep click',(await setDecision(b,'possible_duplicate',0,'mark-keep-button','Keep')).includes('Keep'));rec('Keep Both click',(await setDecision(b,'possible_duplicate',1,'mark-keep-both-button','Keep Both')).includes('Keep Both'));rec('Ignore click',(await setDecision(b,'possible_duplicate',2,'mark-ignore-button','Ignore')).includes('Ignore'));rec('Review Later click and note',(await setDecision(b,'wrong_period',0,'mark-review-later-button','Review Later',true)).includes('Review Later'));
await click(b,'nav-reports');await click(b,'nav-review_center');let wrong=await categoryCards(b,'wrong_period');await wrong[0].click();rec('Note persists after navigation',(await b.$('[data-testid="finding-note-input"]').getValue())===NOTE,NOTE);let files=await exportSet(b,'Before restart');if(files.length===3){execFileSync('python',[path.resolve(__dirname,'validate_export_files.py'),...files],{stdio:'inherit'});rec('Exported files readable and safe',true,files.join(', '),'FILE VALIDATION')}
await deleteChecks(b);await b.deleteSession();b=null;d.kill();d=null;await sleep(2500);rec('No orphan processes after shutdown',pcount()===0,`${pcount()} processes`,'RUNTIME');({b,d,up}=await session());rec('Relaunch backend connects',up,'fresh session','API/BACKEND');await enterApp(b);await openClientReview(b,CLIENT);let post=await b.$$('[data-testid="exception-card-item"]');rec('Findings persist after restart',post.length===25,`${post.length} findings`);let w=await categoryCards(b,'wrong_period');await w[0].click();rec('Review note persists after restart',(await b.$('[data-testid="finding-note-input"]').getValue())===NOTE,NOTE);let files2=await exportSet(b,'After restart');if(files2.length===3){execFileSync('python',[path.resolve(__dirname,'validate_export_files.py'),...files2],{stdio:'inherit'});rec('Restart exports readable and safe',true,files2.join(', '),'FILE VALIDATION')}
await b.deleteSession();b=null;d.kill();d=null;await sleep(2500);rec('No orphan processes after restart shutdown',pcount()===0,`${pcount()} processes`,'RUNTIME');
}catch(e){rec('Unhandled independent UI failure',false,e.stack||e.message)}finally{if(b)try{await b.deleteSession()}catch{};if(d)try{d.kill()}catch{};kill()}fs.writeFileSync('final_independent_results.json',JSON.stringify(results,null,2));console.log(`FINAL ${results.filter(x=>x.pass).length}/${results.length}`);process.exit(results.every(x=>x.pass)?0:1)})();